using System.Reflection;

[assembly: AssemblyTitle("EPiServer 404 Handler")]
[assembly: AssemblyDescription("Custom 404 Handler for EPiServer. See https://github.com/Geta/404handler")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("BV Network AS and Geta")]
[assembly: AssemblyProduct("Geta.404Handler")]
[assembly: AssemblyCopyright("BV Network AS and Geta 2020")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("")]
[assembly: AssemblyKeyName("")]
[assembly: AssemblyVersion("1.1.0")]
[assembly: AssemblyFileVersion("1.1.0.0")]
[assembly: AssemblyInformationalVersion("1.1.0")]
