using System.Reflection;

[assembly: AssemblyTitle("BV Network 404 Handler")]
[assembly: AssemblyDescription("Custom 404 Handler for EPiServer. See https://github.com/BVNetwork/404handler")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("BV Network AS and Geta")]
[assembly: AssemblyProduct("")]
[assembly: AssemblyCopyright("BV Network AS and Geta 2017")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("")]
[assembly: AssemblyKeyName("")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]